using System.Windows.Input;

namespace Body_Distribution_Studio.ViewModels;

public sealed class PreviewViewModel : ViewModelBase
{
    private string _yamlContent;

    public string YamlContent
    {
        get => _yamlContent;
        set => SetField(ref _yamlContent, value);
    }

    // Placeholder commands — generation logic is not implemented yet.
    public ICommand GenerateCommand { get; } = new RelayCommand(() => { });
    public ICommand CopyCommand { get; } = new RelayCommand(() => { });
    public ICommand SaveCommand { get; } = new RelayCommand(() => { });
    public ICommand ExportCommand { get; } = new RelayCommand(() => { });

    public PreviewViewModel()
    {
        _yamlContent =
            """
            # Body Distribution — DBD Configuration
            # Generated by Formsmith

            version: 1

            texturePacks:
              - name: Fair Skin
                mappings:
                  - vanilla: textures/actors/character/femalebody_1.dds
                    replacement: textures/dbd/FairSkin/femalebody_1.dds
                  - vanilla: textures/actors/character/femalebody_msn.dds
                    replacement: textures/dbd/FairSkin/femalebody_msn.dds
              - name: Tempered
                mappings:
                  - vanilla: textures/actors/character/femalebody_1.dds
                    replacement: textures/dbd/Tempered/femalebody_1.dds

            rules:
              - name: Nord Females
                texturePack: Fair Skin
                bodySlidePreset: CBBE Curvy
                priority: 2
                conditions:
                  - type: Race
                    operator: "=="
                    value: Nord
                  - type: Sex
                    operator: "=="
                    value: Female
              - name: Bandits
                texturePack: Tempered
                bodySlidePreset: BHUNP Slim
                priority: 1
                conditions:
                  - type: Faction
                    operator: "=="
                    value: Bandits
                  - type: Sex
                    operator: "=="
                    value: Female
              - name: Fallback
                texturePack: Fair Skin
                bodySlidePreset: CBBE Curvy
                priority: 0
                conditions:
                  - type: Sex
                    operator: "=="
                    value: Female
            """;
    }
}
